export default [
  {
    employer_name: "Goli Tech",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_id: "9uRtu1BdtPQAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:
      "https://www.ziprecruiter.com/c/Goli-Tech/Job/React-Developer/-in-Florham-Park,NJ?jid=71e35414eedfd773",
    job_description:
      "Required Qualifications:\n• 6+ years of experience with modern HTML, CSS, JavaScript (ES6+), Typescript, and writing clean and developer-friendly code.\n• 6+ years of experience supporting at least 2 publicly available Web applications using React/NextJS, supported by RESTful web services.\n\nDesired Qualifications:\n• Advanced knowledge of ReactJS, and NextJS Architecture.\n• Min 3+ years of experience supporting Web applications using Typescript.\n• Experience with creating large-scale Web Applications, specifically with ReactJS.\n• Experience creating near-pixel-perfect, robust, developer-friendly code for user interfaces / Web Applications.\n• Experience with ReactJS, NextJS, React Testing Library (RTL), Webpack, and StencilJS.\n• Experience building Restful API and web services using nodeJS\n• Experience with complex state management, specifically with other state management tools like Redux, RxJS or other similar.\n• Experience writing and UI unit tests (Jest, Jasmine, etc.)\n• Experience with guidance and mentoring of other developers while working on projects and initiatives.\n• Familiarity with web Application performance.\n• Advanced Git skills\n\nRequired Skills : Redux,React,HTML,Javascript\nBasic Qualification :\nAdditional Skills : Web Developer,Software Developer\nBackground Check :Yes",
    job_is_remote: false,
    job_posted_at_timestamp: 1679602799,
    job_posted_at_datetime_utc: "2023-03-23T20:19:59.000Z",
    job_city: "Florham Park",
    job_state: "NJ",
    job_country: "US",
    job_latitude: 40.787876,
    job_longitude: -74.38821,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=9uRtu1BdtPQAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-23T00:00:00.000Z",
    job_offer_expiration_timestamp: 1682208000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 72,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "6+ years of experience with modern HTML, CSS, JavaScript (ES6+), Typescript, and writing clean and developer-friendly code",
        "6+ years of experience supporting at least 2 publicly available Web applications using React/NextJS, supported by RESTful web services",
        "Required Skills : Redux,React,HTML,Javascript",
        "Additional Skills : Web Developer,Software Developer",
        "Background Check :Yes",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "Symplore",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkgSbwFcT_qgR8b3tbYxACftJXeWOHIp9NXmJf&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "EBJa8AyNdR4AAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-symplore-3535549095",
    job_description:
      "Hi,\n\nHope you are doing great.\n\nWe have an immediate requirement for below position please go through it and let me know your interest by sharing your updated resume and expected hourly rate.\n\nPosition: React-Native Mobile Developer\n\nLocation: Atlanta, Georgia / Need Locals\n\nDuration: 14 Months\n\nClient: Apex\n\nVisa Restrictions: None\n\nRole: W2\n\nMUST be a US Citizen, Green card holder, TN Visa, or EAD who can work on W-2\n\nRequired Skills\n\nReact Native - Mobile Development SQL Communication with Offshore Teams\n\nBasic Qualifications\n\nAdditional Skills\n\nPython Angular\n\nJob Description\n\nNext Career Move - Mobile React Developer\n\nWhat would motivate you to make a move from your current role?\n\nCompany Overview: One of the largest Oil and Gas Distributors across the U.S\n\nOur client is one of the largest operator of travel centers in North America with more than 600+Â locations in the U.S. The company employs more than 20,000 people. The company has embraced technology and moved in new directions, leading the company's growth from 1.1 billion gallons sold in 1996 to more than 7 billion sold annually today. Our client has served more than 1.6 million guests a day and is committed to connecting people and places with comfort, care and a smile at every stop. Come join our team and help us connect the world with our services!\n\nPosition:\n\nOur client is rapidly expanding and looking to make a move towards mobile development. The company is looking to build a mobile application to assist the truck-drivers out on the road find lodging, fuel stops, calculate expenses, and keep track of workflow changes. This application will assist the lives of the truck-drivers and make their work-life balance much simpler, allowing them to finish and come home sooner. The mobile application team is looking to add on a senior developer to help build out this application and provide guidance to the younger developers. The team is working on a React-Native mobile platform that works in conjunction with Angular and Python technologies. If you're looking for a growth opportunity that will help the lives of the hard-working then this is your chance!\n\nPerks:\n• Work with a top 500 company in an award-winning work environment\n• Great pay ranges\n• Chance for long-term employment to become permanent\n• Learning and development courses to enhance your skills/certs\n• Wide array of benefits: Vision, Dental, Health, 401K\n• Work within an expanding team that will offer the potential for career growth\n• Work fully remote from your home-office\n\nResponsibilities:\n• Develop code in React-native language\n• Participate in high-level development, design, and mentoring\n• Collaborate with the development team\n• Contribute to core application changes\n• Implement new mobile features such as Geofencing and others\n• Conduct periodic code reviews with the development team\n• Help integrate the workflow portal onto a mobile platform\n• Provide knowledge and expertise to Junior Engineers\n• Ability to work fully remote from your home office\n• Work with a wide-array of newer technologies: React-Native, Angular, Python, and others\n\nQualifications\n• Bachelor's degree or higher in an Engineering or Science field, or related work experience\n• Ability to communicate effectively to multiple teams\n• Experience with React-Native\n• Experience with Angular or Python coding\n• Mobile Software Engineering knowledge and understanding of common terminology\n• Ability to work hybrid around Atlanta or Knoxville\n• MUST be a US Citizen, Green card holder, TN Visa, or EAD who can work on W-2",
    job_is_remote: false,
    job_posted_at_timestamp: 1679689643,
    job_posted_at_datetime_utc: "2023-03-24T20:27:23.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: ["health_insurance", "dental_coverage", "retirement_savings"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=EBJa8AyNdR4AAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-23T20:27:23.000Z",
    job_offer_expiration_timestamp: 1682281643,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: [
      "Angular",
      "React.js",
      "React Native",
      "Learning",
      "Employee Benefits",
      "Code Review",
      "SQL",
      "Mobile Application Development",
      "Python (Programming Language)",
      "Mobile Applications",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "MUST be a US Citizen, Green card holder, TN Visa, or EAD who can work on W-2",
        "React Native - Mobile Development SQL Communication with Offshore Teams",
        "Work with a wide-array of newer technologies: React-Native, Angular, Python, and others",
        "Bachelor's degree or higher in an Engineering or Science field, or related work experience",
        "Ability to communicate effectively to multiple teams",
        "Experience with React-Native",
        "Experience with Angular or Python coding",
        "Mobile Software Engineering knowledge and understanding of common terminology",
        "Ability to work hybrid around Atlanta or Knoxville",
      ],
      Responsibilities: [
        "The company is looking to build a mobile application to assist the truck-drivers out on the road find lodging, fuel stops, calculate expenses, and keep track of workflow changes",
        "This application will assist the lives of the truck-drivers and make their work-life balance much simpler, allowing them to finish and come home sooner",
        "Develop code in React-native language",
        "Participate in high-level development, design, and mentoring",
        "Collaborate with the development team",
        "Contribute to core application changes",
        "Implement new mobile features such as Geofencing and others",
        "Conduct periodic code reviews with the development team",
        "Help integrate the workflow portal onto a mobile platform",
        "Provide knowledge and expertise to Junior Engineers",
      ],
      Benefits: [
        "Work with a top 500 company in an award-winning work environment",
        "Great pay ranges",
        "Chance for long-term employment to become permanent",
        "Learning and development courses to enhance your skills/certs",
        "Wide array of benefits: Vision, Dental, Health, 401K",
        "Work within an expanding team that will offer the potential for career growth",
        "Work fully remote from your home-office",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "VeeAR Projects Inc.",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfuwt3yzkMbdq86OAM9fPxBN4rVYZPoiKmzfUg&s=0",
    employer_website: "http://veearprojects.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "k32YrPEXSfcAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-veear-projects-inc-3535521779",
    job_description:
      "Title: React Developer\n\nDuration: 12 months contract\n\nLocation: New York City, NY (Onsite)\n\nJob Description:\n\nPurpose: Create React components in support of a new data visualization project.\n\nResponsibilities:\n• Develop components using ReactJS.\n• Implement animations for data update events.\n• Ensure accessibility features are properly supported.\n• Work with designers to ensure specifications are met.\n• Collaborate with other developers on consistent code style.\n\nRequirements\n• Strong JavaScript and CSS foundation\n• Experience working with ReactJS.\n• Comfortable using command line tools like Git.\n\nTechnologies\n• JavaScript\n• HTML/CSS\n• ReactJS\n• Storybook\n• Webpack",
    job_is_remote: false,
    job_posted_at_timestamp: 1679700751,
    job_posted_at_datetime_utc: "2023-03-24T23:32:31.000Z",
    job_city: "New City",
    job_state: "NY",
    job_country: "US",
    job_latitude: 41.147594,
    job_longitude: -73.9893,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=k32YrPEXSfcAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-05-23T17:29:35.000Z",
    job_offer_expiration_timestamp: 1684862975,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 40,
    job_max_salary: 80,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "Strong JavaScript and CSS foundation",
        "Experience working with ReactJS",
        "Comfortable using command line tools like Git",
      ],
      Responsibilities: [
        "Purpose: Create React components in support of a new data visualization project",
        "Develop components using ReactJS",
        "Implement animations for data update events",
        "Ensure accessibility features are properly supported",
        "Work with designers to ensure specifications are met",
        "Collaborate with other developers on consistent code style",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "_uJj6OkSMCEAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-dice-3542688081",
    job_description:
      "Title: React Developer\n\nDuration: 12 months contract\n\nLocation: New York City, NY (Onsite)\n\nJob Description:\n\nPurpose: Create React components in support of a new data visualization project.\n\nResponsibilities:\n• Develop components using ReactJS.\n• Implement animations for data update events.\n• Ensure accessibility features are properly supported.\n• Work with designers to ensure specifications are met.\n• Collaborate with other developers on consistent code style.\n\nRequirements\n• Strong JavaScript and CSS foundation\n• Experience working with ReactJS.\n• Comfortable using command line tools like Git.\n\nTechnologies\n• JavaScript\n• HTML/CSS\n• ReactJS\n• Storybook\n• Webpack",
    job_is_remote: false,
    job_posted_at_timestamp: 1679713023,
    job_posted_at_datetime_utc: "2023-03-25T02:57:03.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
    job_latitude: 40.712776,
    job_longitude: -74.005974,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=_uJj6OkSMCEAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-24T02:57:03.000Z",
    job_offer_expiration_timestamp: 1682305023,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong JavaScript and CSS foundation",
        "Experience working with ReactJS",
        "Comfortable using command line tools like Git",
      ],
      Responsibilities: [
        "Purpose: Create React components in support of a new data visualization project",
        "Develop components using ReactJS",
        "Implement animations for data update events",
        "Ensure accessibility features are properly supported",
        "Work with designers to ensure specifications are met",
        "Collaborate with other developers on consistent code style",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "ocgdaeLHgzgAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React developer",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/React-developer_~0177a6be660ae49b1b/",
    job_description:
      "We have several projects and need help with some tasks/modules. We will be glad if you are familiar with cryptocurrency and crypto projects (exchanges, dex, nft marketplaces).",
    job_is_remote: true,
    job_posted_at_timestamp: 1679568392,
    job_posted_at_datetime_utc: "2023-03-23T10:46:32.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ocgdaeLHgzgAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: ["React", "JavaScript", "Redux", "TypeScript"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 20,
    job_max_salary: 25,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {},
    job_job_title: null,
  },
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "TQwrdGI2gnEAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Java/React Developer- Hybrid Model",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/java-react-developer-hybrid-model-at-dice-3542687315",
    job_description:
      "Note: Plano TX, Columbus OH, Chicago IL , NC, New york, New Jersey, Tampa FL, Wilmington Delaware, Ohio, Charlotte NC(Hybrid Model - 2 day Office).\n\nDescription:\n\nThe candidate must be a top-notch Java developer committed to becoming an integral part of and fostering growth within our development team.\n\nDevelop user interface components and implementing them following well-known React.js workflows (such as Flux or Redux).\n\nStrong proficiency in JavaScript, including DOM manipulation and the JavaScript object model.\n\nThorough understanding of React.js and its core principles.\n\nThanks and Regards,\n\nApton\n• provided by Dice",
    job_is_remote: true,
    job_posted_at_timestamp: 1679713024,
    job_posted_at_datetime_utc: "2023-03-25T02:57:04.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=TQwrdGI2gnEAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-24T02:57:04.000Z",
    job_offer_expiration_timestamp: 1682305024,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The candidate must be a top-notch Java developer committed to becoming an integral part of and fostering growth within our development team",
        "Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model",
        "Thorough understanding of React.js and its core principles",
      ],
      Responsibilities: [
        "Develop user interface components and implementing them following well-known React.js workflows (such as Flux or Redux)",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "HustleFish",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Salary.com",
    job_id: "xjcmlBtPkJAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Front-End React Developer",
    job_apply_link:
      "https://www.salary.com/job/hustlefish/front-end-react-developer/j202303230542321197462",
    job_description:
      "Hustlefish is digital content, strategy and development agency. We are looking for a great JavaScript developer who is proficient with React.js. Your focus will be divided between building robust and easy-to-maintain react/next.js applications and developing a custom react full-site editor within WordPress Gutenberg system. In both, you will coordinate with the rest of the team working on different layers of the applications/infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality products is important. You will require to do occasional and minimal PHP development within a WordPress environment to implement these react projects.\n• 2 years experience with React.\n• 5 years of development experience.\n• Strong communicator.\n• Experience building both class components and functional components.\n• Ability to work independently or on a team depending on project scale.\n• An understanding of common programming paradigms and fundamental React principles, such as React components, hooks, and the React lifecycle.\n• High design fidelity in front-end development.\n• Proficient with the latest versions of ECMAScript (JavaScript), HTML and CSS.\n• Familiarity with RESTful APIs (GraphQL is a plus).\n• Experience with common front-end development tools like Babel, Webpack, NPM.\n• Familiarity with Git\n• Health Care Plan (Medica, Dental & Vision)\n• Unlimited Paid Time Off (Vacation, Sick & Public Holidays)\n• Family Leave (Maternity, Paternity)\n• Flexible Woke From Home\n• Paid Membership to Your Local Co-working Spacke\n• Reimbursement for Ome office Setup ($1,000)\n• Monthly health insurance stipend.\n• Competitive Salary ($75,000 - $100,000 Based on Experience)\n• Yearly Bonus and Raises",
    job_is_remote: false,
    job_posted_at_timestamp: 1679616000,
    job_posted_at_datetime_utc: "2023-03-24T00:00:00.000Z",
    job_city: "Zionsville",
    job_state: "IN",
    job_country: "US",
    job_latitude: 39.950874,
    job_longitude: -86.26194,
    job_benefits: ["health_insurance", "paid_time_off", "dental_coverage"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=xjcmlBtPkJAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-09-23T00:00:00.000Z",
    job_offer_expiration_timestamp: 1695427200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 24,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "You will require to do occasional and minimal PHP development within a WordPress environment to implement these react projects",
        "2 years experience with React",
        "5 years of development experience",
        "Strong communicator",
        "Experience building both class components and functional components",
        "Ability to work independently or on a team depending on project scale",
        "An understanding of common programming paradigms and fundamental React principles, such as React components, hooks, and the React lifecycle",
        "High design fidelity in front-end development",
        "Proficient with the latest versions of ECMAScript (JavaScript), HTML and CSS",
        "Experience with common front-end development tools like Babel, Webpack, NPM",
        "Familiarity with Git",
      ],
      Responsibilities: [
        "Your focus will be divided between building robust and easy-to-maintain react/next.js applications and developing a custom react full-site editor within WordPress Gutenberg system",
        "In both, you will coordinate with the rest of the team working on different layers of the applications/infrastructure",
        "Therefore, a commitment to collaborative problem solving, sophisticated design, and quality products is important",
      ],
      Benefits: [
        "Health Care Plan (Medica, Dental & Vision)",
        "Unlimited Paid Time Off (Vacation, Sick & Public Holidays)",
        "Family Leave (Maternity, Paternity)",
        "Flexible Woke From Home",
        "Paid Membership to Your Local Co-working Spacke",
        "Reimbursement for Ome office Setup ($1,000)",
        "Monthly health insurance stipend",
        "Competitive Salary ($75,000 - $100,000 Based on Experience)",
        "Yearly Bonus and Raises",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "ICS, A Korn Ferry company",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKVwJFdGk7HMkS8e9j_5eGOBPensLFMTG3IzOB&s=0",
    employer_website: "http://www.infinity-cs.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "s4NrBu3w8vcAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-ics-a-korn-ferry-company-3536054349",
    job_description:
      "TITLE: React Developer\n\nLocation: Houston, Texas\n\nCompensation Range : $40-80/hr\n\nJob Description\n\nLong term- multiyear contract in Houston! Our client is looking for MULTIPLE React Developers to join their team!\n\nYou will be working on real-time operation applications, the React Developer will work with a team of mid to senior level software engineers on front-end, new application development, as well as enhancing and supporting existing in-house developed applications.\n\nThe role will involve working with the Solutions Engineers, Data Engineers and end users to help identify requirements. Will also be responsible for analyzing requirements, and to architect, design and present solutions to the business problems.\n\nReact.js - Experience & Skills\n• Must have development experience with React/Redux/Material-UI.\n• Experience with building commercial and/or enterprise applications is preferred.\n• Oil and Gas exploration and production experience is a plus.\n• Individual should be flexible and able to adapt to a dynamic environment.\n• Individual should be self-motivated who can work independently with minimal supervision, and also work well as part of a team.\n• Should have good communication skills and the willingness and ability to jump into existing projects.\n• Bachelor's degree in related field is preferred; High school diploma or GED required.\n\nAbout Infinity Consulting Solutions\n\nAt Infinity Consulting Solutions our mission is to cultivate successful long term relationships with candidates and clients matching the right candidate with the right client. We believe technology cannot replace the real personal relationships we cultivate. We reject the notion that technology alone is the answer to staffing which is why we our successful partnerships rely on collaboration NOT automation. ICS has been providing flexible staffing solutions for over 20 years in Information Technology, Compliance, Accounting / Finance and Corporate Support. Our staffing solutions include Contract, Temp to Perm and Permanent Placement.\n\nICS is an Equal Opportunity Employer.\n• W2 employees of ICS are offered comprehensive benefits including health, dental and vision.",
    job_is_remote: false,
    job_posted_at_timestamp: 1679597727,
    job_posted_at_datetime_utc: "2023-03-23T18:55:27.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: ["retirement_savings", "health_insurance", "dental_coverage"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=s4NrBu3w8vcAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-22T18:55:27.000Z",
    job_offer_expiration_timestamp: 1682189727,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Must have development experience with React/Redux/Material-UI",
        "Individual should be flexible and able to adapt to a dynamic environment",
        "Individual should be self-motivated who can work independently with minimal supervision, and also work well as part of a team",
        "Should have good communication skills and the willingness and ability to jump into existing projects",
      ],
      Responsibilities: [
        "You will be working on real-time operation applications, the React Developer will work with a team of mid to senior level software engineers on front-end, new application development, as well as enhancing and supporting existing in-house developed applications",
        "The role will involve working with the Solutions Engineers, Data Engineers and end users to help identify requirements",
        "Will also be responsible for analyzing requirements, and to architect, design and present solutions to the business problems",
      ],
      Benefits: [
        "Compensation Range : $40-80/hr",
        "W2 employees of ICS are offered comprehensive benefits including health, dental and vision",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "Allegis Group",
    employer_logo:
      "https://www.allegisgroup.com/-/media/images/allegisgroup/global/logos/ag-horizontal-logo-png.png",
    employer_website: "http://www.allegisgroup.com",
    employer_company_type: "Staffing",
    job_publisher: "LinkedIn",
    job_id: "sRYom5JPXLAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Javascript/React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/javascript-react-developer-at-allegis-group-3537424467",
    job_description:
      "***CANDIDATES MUST BE ABLE TO WORK ON TEKSYSTEMS DIRECT W2***\n\nMUST BE ABLE TO GO ON-SITE IN CUPERTINO, CA\n\nDescription\n\nJob Summary:\n\nThe autonomous visualization systems team is in search of a curious and innovative team player who is passionate about leveraging cutting edge web technology to deliver experiences that surpass user expectations. Our team works on many impactful web applications and services with high expectations of quality and performance.\n\nAs a Sr Front End Engineer, your responsibilities will include all phases of user interface development. From architecture and design to implementation and customer engagement. You will work with our internal customers and backend developers both on our team and others. We are looking for someone that has an eye for design, is able to communicate well with members outside our team and play an active role in the future roadmap of our applications.\n\nQualifications\n• 4+ years professional experience building responsive, use friendly web geospatial intelligence applications\n• Proficient understanding of base front end development technologies including HTML5/CSS3/JavaScript\n• Significant experience with JavaScript frameworks and client side state management using React.js/Redux\n• Experience in developing secure web applications and knowledge of application vulnerabilities such as Cross Site Scripting (XSS), Cross Site Request Forgery (CSRF), etc\n• Good Communication and Interpersonal Skills\n\nBuilding reusable components and front-end libraries with Storybook\n\nTop Skills Details\n\nJavaScript,React.js, React, HTML, CSS, Responsive Web design, API, Redux\n\nAdditional Skills & Qualifications\n\nIf this person has node that would be helpful, but this is purely a front end react role.\n\nExperience Level\n\nExpert Level\n\n40HRS/WK\n\nAbout TEKsystems\n\nWe're partners in transformation. We help clients activate ideas and solutions to take advantage of a new world of opportunity. We are a team of 80,000 strong, working with over 6,000 clients, including 80% of the Fortune 500, across North America, Europe and Asia. As an industry leader in Full-Stack Technology Services, Talent Services, and real-world application, we work with progressive leaders to drive change. That's the power of true partnership. TEKsystems is an Allegis Group company.\n\nThe company is an equal opportunity employer and will consider all applications without regards to race, sex, age, color, religion, national origin, veteran status, disability, sexual orientation, gender identity, genetic information or any characteristic protected by law.",
    job_is_remote: false,
    job_posted_at_timestamp: 1679647180,
    job_posted_at_datetime_utc: "2023-03-24T08:39:40.000Z",
    job_city: "Cupertino",
    job_state: "CA",
    job_country: "US",
    job_latitude: 37.322998,
    job_longitude: -122.03218,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=sRYom5JPXLAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-23T08:39:40.000Z",
    job_offer_expiration_timestamp: 1682239180,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 48,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "***CANDIDATES MUST BE ABLE TO WORK ON TEKSYSTEMS DIRECT W2***",
        "MUST BE ABLE TO GO ON-SITE IN CUPERTINO, CA",
        "4+ years professional experience building responsive, use friendly web geospatial intelligence applications",
        "Proficient understanding of base front end development technologies including HTML5/CSS3/JavaScript",
        "Significant experience with JavaScript frameworks and client side state management using React.js/Redux",
        "Experience in developing secure web applications and knowledge of application vulnerabilities such as Cross Site Scripting (XSS), Cross Site Request Forgery (CSRF), etc",
        "Good Communication and Interpersonal Skills",
        "Building reusable components and front-end libraries with Storybook",
        "JavaScript,React.js, React, HTML, CSS, Responsive Web design, API, Redux",
        "If this person has node that would be helpful, but this is purely a front end react role",
      ],
      Responsibilities: [
        "As a Sr Front End Engineer, your responsibilities will include all phases of user interface development",
        "From architecture and design to implementation and customer engagement",
        "You will work with our internal customers and backend developers both on our team and others",
        "We are looking for someone that has an eye for design, is able to communicate well with members outside our team and play an active role in the future roadmap of our applications",
      ],
    },
    job_job_title: null,
  },
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "8hN6UmxlMAEAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Senior React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-react-developer-at-dice-3542686219",
    job_description:
      "Title: Senior React Developer\n\nDuration: 6+ Month Contract to Hire\n\nLocation: Cleveland-Hybrid onsite 3 days a week\n\nVISA: (Must on W2)\n\nKnowledge & Experience:\n• 5+ years IT experience.\n• 5+ years with CSS and/or HTML.\n• 3+ years with CSS 3 and/or HTML5.\n• 3+ years with JavaScript.\n• 3+ years in React.\n• 5+ years of object-oriented analysis and design.\n• Experience with version control systems such as git, mercurial, or subversion.\n• Experience with command line tools.\n• Experience working on all phases of the Software Development Lifecycle.\n• Experience working as part of an enterprise web team, interfacing with other developers, designers, web engineers, and external agencies or partners.\n\nFormal Education & Certification:\n• Bachelor degree or foreign equivalent in related field or equivalent experience.\n- provided by Dice",
    job_is_remote: false,
    job_posted_at_timestamp: 1679616000,
    job_posted_at_datetime_utc: "2023-03-24T00:00:00.000Z",
    job_city: "Cleveland",
    job_state: "OH",
    job_country: "US",
    job_latitude: 41.49932,
    job_longitude: -81.69436,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=8hN6UmxlMAEAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-04-24T02:40:38.000Z",
    job_offer_expiration_timestamp: 1682304038,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "VISA: (Must on W2)",
        "5+ years IT experience",
        "5+ years with CSS and/or HTML",
        "3+ years with CSS 3 and/or HTML5",
        "3+ years with JavaScript",
        "3+ years in React",
        "5+ years of object-oriented analysis and design",
        "Experience with version control systems such as git, mercurial, or subversion",
        "Experience with command line tools",
        "Experience working on all phases of the Software Development Lifecycle",
        "Experience working as part of an enterprise web team, interfacing with other developers, designers, web engineers, and external agencies or partners",
        "Bachelor degree or foreign equivalent in related field or equivalent experience",
        "provided by Dice",
      ],
    },
    job_job_title: "Senior",
  },
];
